%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 720
distortion_parameters:
   k1: -6.4672351701841341e-03 #0.1112652712380454
   k2: 2.6413890848851568e-01 #-0.210068316873627
   p1: 3.0504877897526584e-04 #0.0009645792209857979
   p2: -2.0219963759718212e-03 #-0.001180816701089352
   # k1: -3.4929395225682870e-02
   # k2: 5.6258262845939933e-01
   # p1: 3.7707684584517721e-03 
   # p2: -5.2330344027061134e-04
projection_parameters:
   fx: 9.1530822206975677e+02  #1003.58113733265
   fy: 9.1478366098762478e+02 #1002.849350672291
   cx: 6.3303872736892640e+02 #641.0791163037911
   cy: 3.6836350514349613e+02 #371.3750331068263
   # fx: 9.1249803100242571e+02
   # fy: 9.1530306150263289e+02
   # cx: 6.3805384676215010e+02
   # cy: 3.7571673374327833e+02

