%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 720
distortion_parameters:
   k1: -1.0605617996822274e-02
   k2: 3.5053576714038104e-01
   p1: 1.9394665116898192e-04
   p2: -1.2765578177239367e-03
   # k1: -4.2183530035731776e-02
   # k2: 5.7811464126119771e-01
   # p1: 1.8756106955193756e-03
   # p2: 2.6323042232111941e-03
projection_parameters:
   fx: 9.2111641259336932e+02
   fy: 9.2026208596556057e+02
   cx: 6.3390840584697833e+02
   cy: 3.6960226179093604e+02
   # fx: 9.1876766840316361e+02
   # fy: 9.2116380720263999e+02
   # cx: 6.4224479433093916e+02
   # cy: 3.7253933418870190e+02
   

