%YAML:1.0
---
File TableParam05 Write: SUCCESS
allCharucoCornersSize: 9
idxNum: 9
idxNum1: 9
idxNum2: 9
average reProjerror err Left0: 1.8119057619146089e-01
average reProjerror err Left1: 1.8326577265689784e-01
average reProjerror err Left2: 1.6442090947792834e-01
average reProjerror err Left3: 2.1887430403188138e-01
average reProjerror err Left4: 3.2720774923639356e-01
average reProjerror err Left5: 1.9780473536197751e-01
average reProjerror err Left6: 1.6588134687441375e-01
average reProjerror err Left7: 2.0987867039824215e-01
average reProjerror err Left8: 1.8846325848364323e-01
average reProjerror err Right0: 1.7618595464515613e-01
average reProjerror err Right1: 1.7746972594996366e-01
average reProjerror err Right2: 1.6690061260745520e-01
average reProjerror err Right3: 2.3479909120039760e-01
average reProjerror err Right4: 2.9051581435915552e-01
average reProjerror err Right5: 2.2297762718086328e-01
average reProjerror err Right6: 1.4602949453455863e-01
average reProjerror err Right7: 1.7187801384812657e-01
average reProjerror err Right8: 1.3129007534342058e-01
Lefterror: 2.0939921112723034e-01
Righterror: 1.9656653704656418e-01
Left camera Matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.0262532425428458e+02, 0., 6.3261298702217778e+02, 0.,
       9.0220567583497268e+02, 3.6545413197665357e+02, 0., 0., 1. ]
Left distCoeffs: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 2.3844262740475131e-02, -8.0220665986497672e-02,
       -2.2325072389236514e-04, -2.2409767523513730e-03, 0. ]
Right camera Matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.2235372379835974e+02, 0., 6.3617785214552487e+02, 0.,
       9.2129474094340776e+02, 3.7437863485971303e+02, 0., 0., 1. ]
Right distCoeffs: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 3.7563659389636801e-02, -1.1093436773885282e-01,
       1.5978025072111511e-03, -6.1281531606456195e-04, 0. ]
rvecs: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -6.7574437069497478e-02, -2.8464268093914478e+00,
       -1.4848316194096731e-01 ]
tvecs: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 8.8275494295200374e-01, -5.3807659245271078e-01,
       1.6950838035747398e+00 ]
LeftError: 2.0939964056015015e-01
RightError: 1.9656519591808319e-01
valid Rows: 9
Read intrinsics: SUCCESS
ret error: 2.0407709438313096e-01
KLeft Stereo: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.1530822206975677e+02, 0., 6.3303872736892640e+02, 0.,
       9.1478366098762478e+02, 3.6836350514349613e+02, 0., 0., 1. ]
KRight Stereo: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.2111641259336932e+02, 0., 6.3390840584697833e+02, 0.,
       9.2026208596556057e+02, 3.6960226179093604e+02, 0., 0., 1. ]
DLeft Stereo: !!opencv-matrix
   rows: 1
   cols: 14
   dt: d
   data: [ -6.4672351701841341e-03, 2.6413890848851568e-01,
       3.0504877897526584e-04, -2.0219963759718212e-03, 0., 0., 0.,
       1.0063266900444643e+00, 0., 0., 0., 0., 0., 0. ]
DRight Stereo: !!opencv-matrix
   rows: 1
   cols: 14
   dt: d
   data: [ -1.0605617996822274e-02, 3.5053576714038104e-01,
       1.9394665116898192e-04, -1.2765578177239367e-03, 0., 0., 0.,
       1.2676791029612053e+00, 0., 0., 0., 0., 0., 0. ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9994256865814513e-01, -5.2915101563382281e-03,
       -9.3198339908006494e-03, 5.2111964019252704e-03,
       9.9994926121157068e-01, -8.6208140273788588e-03,
       9.3649782386973496e-03, 8.5717514371020081e-03,
       9.9991940788239997e-01 ]
T: [ -1.0034650988761087e-01, 3.0929553980842399e-04,
    2.7452760642807987e-05 ]
E: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 2.7534842721473237e-06, -2.4800163235151832e-05,
       3.0950727816994638e-04, 9.6719406542063093e-04,
       8.6000007377553839e-04, 1.0033816689471348e-01,
       -8.3220314782261949e-04, -1.0033978178678586e-01,
       8.6795118312273675e-04 ]
F: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.8782313354311368e-09, -1.6926609909736131e-08,
       1.9828957055096407e-04, 6.6036355315658134e-07,
       5.8751224896298853e-07, 6.2070665553108813e-02,
       -7.6815251392889968e-04, -6.3288076780106881e-02, 1. ]
average epipolar err: 1.3673261006673176e-01
R1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9991915701643785e-01, -8.3759337316048569e-03,
       -9.5667740466748689e-03, 8.3346691797124561e-03,
       9.9995582583043163e-01, -4.3450750792411686e-03,
       9.6027455032984821e-03, 4.2649879136118672e-03,
       9.9994479705476524e-01 ]
R2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9999521240185607e-01, -3.0822602537212583e-03,
       -2.7357831618911836e-04, 3.0834094786267798e-03,
       9.9998598096557989e-01, 4.3047018821485783e-03,
       2.6030626936982243e-04, -4.3055248269391220e-03,
       9.9999069730503531e-01 ]
P1: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 2.8083932754969707e+05, 0., -2.2497658764648438e+05, 0., 0.,
       2.8083932754969707e+05, -5.6287419189453125e+04, 0., 0., 0., 1.,
       0. ]
P2: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 2.8083932754969707e+05, 0., -2.2497658764648438e+05,
       -2.8181381279924375e+04, 0., 2.8083932754969707e+05,
       -5.6287419189453125e+04, 0., 0., 0., 1., 0. ]
Q: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1., 0., 0., 2.2497658764648438e+05, 0., 1., 0.,
       5.6287419189453125e+04, 0., 0., 0., 2.8083932754969707e+05, 0.,
       0., 9.9654209550672075e+00, 0. ]
